package com.Eletronics.view;

import com.Eletronics.model.Administrador;
import com.Eletronics.model.Produto;
import com.Eletronics.services.ProdutoServices;
import java.awt.Color;
import com.Eletronics.services.renderers.RenderizadorUm;
import com.Eletronics.services.tools.Warning;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

public class AdministradorMain extends javax.swing.JFrame {
    private BufferedImage imagem;
    private Administrador administrador;
    
    public AdministradorMain() {
        super("ELETRONICS");
        initComponents();
        atualizar.setVisible(false);
        selecionarImagem.setVisible(false);
        getContentPane().setBackground(Color.WHITE);
        Campo_Lista.setCellRenderer(new RenderizadorUm());
        logoTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Eletronics/view/midias/logoTop.png")));
        Campo_Imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Eletronics/view/midias/noProduct.png")));
        Campo_Lista.setModel(ProdutoServices.trazerProdutos());
        Campo_Lista.setSelectedIndex(0);
        this.selecionarProduto();
    }
    
    public AdministradorMain(Administrador administrador) {
        super("ELETRONICS");
        initComponents();
        atualizar.setVisible(false);
        this.administrador = administrador;
        selecionarImagem.setVisible(false);
        getContentPane().setBackground(Color.WHITE);
        Campo_Lista.setCellRenderer(new RenderizadorUm());
        logoTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Eletronics/view/midias/logoTop.png")));
        Campo_Imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Eletronics/view/midias/noProduct.png")));
        Campo_Lista.setModel(ProdutoServices.trazerProdutos());
        Campo_Lista.setSelectedIndex(0);
        this.selecionarProduto();
    }
    
    private void selecionarProduto() {
        if (Campo_Lista.getModel().getSize() > 0){
            DefaultListModel modelo = (DefaultListModel) Campo_Lista.getModel();
            Produto produto = (Produto) modelo.get(Campo_Lista.getSelectedIndex());
            Campo_Nome.setText(produto.getNome());
            Campo_Descricao.setText(produto.getDescricao());
            Campo_Valor.setText(String.valueOf(produto.getValor()));
            Image image = produto.getImagem().getScaledInstance(180, 234, Image.SCALE_SMOOTH);
            Campo_Imagem.setIcon(new ImageIcon(image));
            selecionarImagem.setVisible(true);
            atualizar.setVisible(false);
        }
    }
    
    private void tornarVisivel(){
        if (Campo_Lista.getSelectedIndex() != -1) {
        DefaultListModel listModel = (DefaultListModel) Campo_Lista.getModel();
            Produto produto = (Produto) listModel.get(Campo_Lista.getSelectedIndex());
            if (!Campo_Nome.getText().equals(produto.getNome()) || !Campo_Descricao.getText().equals(produto.getDescricao()) || !Campo_Valor.getText().equals(String.valueOf(produto.getValor())))
                atualizar.setVisible(true);
            else
                atualizar.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new com.Eletronics.view.TelaInicial.jPanelGradient();
        logoTop = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        profileButton = new javax.swing.JLabel();
        aboutButton = new javax.swing.JLabel();
        productButton = new javax.swing.JLabel();
        logOutButton = new javax.swing.JLabel();
        customerButton = new javax.swing.JLabel();
        administratorButton = new javax.swing.JLabel();
        salesButton = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        Campo_Lista = new javax.swing.JList<>();
        selecionarImagem = new javax.swing.JButton();
        excluir = new javax.swing.JButton();
        Campo_Imagem = new javax.swing.JLabel();
        Campo_Nome = new javax.swing.JTextField();
        atualizar = new javax.swing.JButton();
        Campo_Descricao = new javax.swing.JTextField();
        Campo_Valor = new javax.swing.JTextField();

        jLabel2.setFont(new java.awt.Font("Nortar", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("LOGIN");

        jLabel3.setFont(new java.awt.Font("Nortar", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("LOGIN");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(java.awt.Color.darkGray);

        jLabel1.setFont(new java.awt.Font("Nortar", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ELETRONICS");

        profileButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        profileButton.setForeground(new java.awt.Color(204, 204, 204));
        profileButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profileButton.setText("MEU PERFIL");
        profileButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profileButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                profileButtonMouseExited(evt);
            }
        });

        aboutButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        aboutButton.setForeground(new java.awt.Color(204, 204, 204));
        aboutButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aboutButton.setText("SOBRE");
        aboutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aboutButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aboutButtonMouseExited(evt);
            }
        });

        productButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        productButton.setForeground(new java.awt.Color(204, 204, 204));
        productButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productButton.setText("PRODUTOS");
        productButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                productButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                productButtonMouseExited(evt);
            }
        });

        logOutButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logOutButton.setForeground(java.awt.Color.pink);
        logOutButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logOutButton.setText("SAIR");
        logOutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOutButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logOutButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logOutButtonMouseExited(evt);
            }
        });

        customerButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        customerButton.setForeground(new java.awt.Color(204, 204, 204));
        customerButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customerButton.setText("CLIENTES");
        customerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                customerButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                customerButtonMouseExited(evt);
            }
        });

        administratorButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        administratorButton.setForeground(new java.awt.Color(204, 204, 204));
        administratorButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        administratorButton.setText("GESTORES");
        administratorButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                administratorButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                administratorButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                administratorButtonMouseExited(evt);
            }
        });

        salesButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        salesButton.setForeground(new java.awt.Color(204, 204, 204));
        salesButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salesButton.setText("VENDAS");
        salesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salesButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salesButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salesButtonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoTop, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aboutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(profileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                    .addComponent(productButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(logOutButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(customerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(administratorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(salesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(logoTop, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(profileButton)
                .addGap(40, 40, 40)
                .addComponent(salesButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(administratorButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(productButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logOutButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aboutButton)
                .addGap(40, 40, 40))
        );

        jLabel4.setFont(new java.awt.Font("Nortar", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("ELETRONICS");

        jLabel5.setFont(new java.awt.Font("Nortar", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("STORE");

        scrollPane.setBackground(new java.awt.Color(255, 255, 255));
        scrollPane.setBorder(null);
        scrollPane.setForeground(new java.awt.Color(0, 0, 0));
        scrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Campo_Lista.setBackground(new java.awt.Color(255, 255, 255));
        Campo_Lista.setBorder(null);
        Campo_Lista.setForeground(new java.awt.Color(0, 0, 0));
        Campo_Lista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Campo_ListaMouseClicked(evt);
            }
        });
        scrollPane.setViewportView(Campo_Lista);

        selecionarImagem.setBackground(new java.awt.Color(255, 255, 255));
        selecionarImagem.setFont(new java.awt.Font("Nortar", 0, 14)); // NOI18N
        selecionarImagem.setForeground(new java.awt.Color(0, 0, 0));
        selecionarImagem.setText("NOVA FOTO");
        selecionarImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionarImagemActionPerformed(evt);
            }
        });

        excluir.setBackground(new java.awt.Color(0, 0, 0));
        excluir.setFont(new java.awt.Font("Nortar", 0, 14)); // NOI18N
        excluir.setForeground(new java.awt.Color(255, 255, 255));
        excluir.setText("EXCLUIR");
        excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirActionPerformed(evt);
            }
        });

        Campo_Imagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Campo_Imagem.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                Campo_ImagemPropertyChange(evt);
            }
        });

        Campo_Nome.setBackground(new java.awt.Color(255, 255, 255));
        Campo_Nome.setForeground(new java.awt.Color(0, 0, 0));
        Campo_Nome.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "nome:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        Campo_Nome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Campo_NomeKeyReleased(evt);
            }
        });

        atualizar.setBackground(new java.awt.Color(255, 255, 255));
        atualizar.setFont(new java.awt.Font("Nortar", 0, 14)); // NOI18N
        atualizar.setForeground(new java.awt.Color(0, 0, 0));
        atualizar.setText("ATUALIZAR");
        atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarActionPerformed(evt);
            }
        });

        Campo_Descricao.setBackground(new java.awt.Color(255, 255, 255));
        Campo_Descricao.setForeground(new java.awt.Color(0, 0, 0));
        Campo_Descricao.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Campo_Descricao.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "descrição:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        Campo_Descricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Campo_DescricaoKeyReleased(evt);
            }
        });

        Campo_Valor.setBackground(new java.awt.Color(255, 255, 255));
        Campo_Valor.setForeground(new java.awt.Color(0, 0, 0));
        Campo_Valor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "valor:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        Campo_Valor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Campo_ValorKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(selecionarImagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Campo_Imagem, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Campo_Nome, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                                    .addComponent(Campo_Descricao, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                                    .addComponent(Campo_Valor, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                                    .addComponent(atualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(excluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Campo_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Campo_Descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Campo_Valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Campo_Imagem, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(selecionarImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void profileButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileButtonMouseEntered
        // TODO add your handling code here:
        profileButton.setForeground(Color.WHITE);
    }//GEN-LAST:event_profileButtonMouseEntered

    private void profileButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileButtonMouseExited
        // TODO add your handling code here:
        profileButton.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_profileButtonMouseExited

    private void aboutButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutButtonMouseEntered
        // TODO add your handling code here:
        aboutButton.setForeground(Color.WHITE);
    }//GEN-LAST:event_aboutButtonMouseEntered

    private void aboutButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutButtonMouseExited
        // TODO add your handling code here:
        aboutButton.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_aboutButtonMouseExited

    private void selecionarImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarImagemActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog(null);
            File arquivo = chooser.getSelectedFile();
            imagem = ImageIO.read(new File(arquivo.getAbsolutePath()));
            Campo_Imagem.setIcon(new ImageIcon(imagem.getScaledInstance(180, 234, Image.SCALE_SMOOTH)));
        } catch (HeadlessException | IOException | NullPointerException e) {
            Warning warning = new Warning("Imagem não encontrada!");
            warning.setVisible(true);
        }
    }//GEN-LAST:event_selecionarImagemActionPerformed

    private void atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarActionPerformed
        // TODO add your handling code here:
        try {
            String nome = Campo_Nome.getText();
            String descricao = Campo_Descricao.getText();
            double valor = Double.parseDouble(Campo_Valor.getText());
            
            DefaultListModel modelo = (DefaultListModel) Campo_Lista.getModel();
            Produto produto = (Produto) modelo.get(Campo_Lista.getSelectedIndex());
            produto.setNome(nome);
            produto.setDescricao(descricao);
            produto.setValor(valor);
            if (imagem != null) produto.setImagem(imagem);
            ProdutoServices.atualizar(produto);
            
            int indice = Campo_Lista.getSelectedIndex();
            Campo_Lista.setModel(ProdutoServices.trazerProdutos());
            atualizar.setVisible(false);
            Campo_Lista.setSelectedIndex(indice);
        } catch (NumberFormatException e) {
            Warning warning = new Warning("Dados incorretos.");
            warning.setVisible(true);
        }
    }//GEN-LAST:event_atualizarActionPerformed

    private void excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirActionPerformed
        // TODO add your handling code here:
        if (Campo_Lista.getModel().getSize() > 0) {
            DefaultListModel modelo = (DefaultListModel) Campo_Lista.getModel();
            Produto produto = (Produto) modelo.get(Campo_Lista.getSelectedIndex());
            ProdutoServices.excluir(produto);
            Campo_Lista.setModel(ProdutoServices.trazerProdutos());
            if (Campo_Lista.getModel().getSize() != 0){
                Campo_Lista.setSelectedIndex(0);
                this.selecionarProduto();
            } else {
                Campo_Nome.setText("");
                Campo_Descricao.setText("");
                Campo_Valor.setText("");
                Campo_Imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Eletronics/view/midias/noProduct.png")));
                selecionarImagem.setVisible(false);
                atualizar.setVisible(false);
            }
        }
    }//GEN-LAST:event_excluirActionPerformed

    
    private void Campo_ListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Campo_ListaMouseClicked
        // TODO add your handling code here:
        this.selecionarProduto();
    }//GEN-LAST:event_Campo_ListaMouseClicked

    private void Campo_NomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Campo_NomeKeyReleased
        // TODO add your handling code here:
        this.tornarVisivel();
    }//GEN-LAST:event_Campo_NomeKeyReleased

    private void Campo_DescricaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Campo_DescricaoKeyReleased
        // TODO add your handling code here:
        this.tornarVisivel();
    }//GEN-LAST:event_Campo_DescricaoKeyReleased

    private void Campo_ValorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Campo_ValorKeyReleased
        // TODO add your handling code here:
        this.tornarVisivel();
    }//GEN-LAST:event_Campo_ValorKeyReleased

    private void Campo_ImagemPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_Campo_ImagemPropertyChange
        // TODO add your handling code here:
        atualizar.setVisible(true);
    }//GEN-LAST:event_Campo_ImagemPropertyChange

    private void productButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productButtonMouseClicked
        // TODO add your handling code here:
        AdministradorProduto administradorProduto = new AdministradorProduto(this.administrador);
        administradorProduto.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_productButtonMouseClicked

    private void productButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productButtonMouseEntered
        // TODO add your handling code here:
        productButton.setForeground(Color.WHITE);
    }//GEN-LAST:event_productButtonMouseEntered

    private void productButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productButtonMouseExited
        // TODO add your handling code here:
        productButton.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_productButtonMouseExited

    private void logOutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutButtonMouseClicked
        // TODO add your handling code here:
        TelaInicial home = new TelaInicial();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logOutButtonMouseClicked

    private void logOutButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutButtonMouseEntered
        // TODO add your handling code here:
        logOutButton.setForeground(Color.red);
    }//GEN-LAST:event_logOutButtonMouseEntered

    private void logOutButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutButtonMouseExited
        // TODO add your handling code here:
        logOutButton.setForeground(Color.pink);
    }//GEN-LAST:event_logOutButtonMouseExited

    private void customerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerButtonMouseClicked
        // TODO add your handling code here:
        AdministradorCliente administradorCliente = new AdministradorCliente(this.administrador);
        administradorCliente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_customerButtonMouseClicked

    private void customerButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerButtonMouseEntered
        // TODO add your handling code here:
        customerButton.setForeground(Color.WHITE);
    }//GEN-LAST:event_customerButtonMouseEntered

    private void customerButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerButtonMouseExited
        // TODO add your handling code here:
        customerButton.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_customerButtonMouseExited

    private void administratorButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_administratorButtonMouseEntered
        // TODO add your handling code here:
        administratorButton.setForeground(Color.WHITE);
    }//GEN-LAST:event_administratorButtonMouseEntered

    private void administratorButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_administratorButtonMouseExited
        // TODO add your handling code here:
        administratorButton.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_administratorButtonMouseExited

    private void administratorButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_administratorButtonMouseClicked
        // TODO add your handling code here:
        AdministradorUsers administradorUsers =  new AdministradorUsers(this.administrador);
        administradorUsers.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_administratorButtonMouseClicked

    private void profileButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileButtonMouseClicked
        // TODO add your handling code here:
        AdministradorPerfil administradorPerfi = new AdministradorPerfil(this.administrador);
        administradorPerfi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_profileButtonMouseClicked

    private void salesButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesButtonMouseEntered
        // TODO add your handling code here:
        salesButton.setForeground(Color.WHITE);
    }//GEN-LAST:event_salesButtonMouseEntered

    private void salesButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesButtonMouseExited
        // TODO add your handling code here:
        salesButton.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_salesButtonMouseExited

    private void salesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesButtonMouseClicked
        // TODO add your handling code here:
        AdministradorVendas administradorVendas = new AdministradorVendas(this.administrador);
        administradorVendas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_salesButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministradorMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministradorMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministradorMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministradorMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministradorMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Campo_Descricao;
    private javax.swing.JLabel Campo_Imagem;
    private javax.swing.JList<String> Campo_Lista;
    private javax.swing.JTextField Campo_Nome;
    private javax.swing.JTextField Campo_Valor;
    private javax.swing.JLabel aboutButton;
    private javax.swing.JLabel administratorButton;
    private javax.swing.JButton atualizar;
    private javax.swing.JLabel customerButton;
    private javax.swing.JButton excluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logOutButton;
    private javax.swing.JLabel logoTop;
    private javax.swing.JLabel productButton;
    private javax.swing.JLabel profileButton;
    private javax.swing.JLabel salesButton;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JButton selecionarImagem;
    // End of variables declaration//GEN-END:variables
}
