/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.Eletronics.view;

import com.Eletronics.model.Cliente;
import com.Eletronics.model.Endereco;
import com.Eletronics.services.CompraServices;
import com.Eletronics.services.EnderecoServices;
import com.Eletronics.services.renderers.RenderizadorCinco;
import com.Eletronics.services.tools.Warning;
import java.awt.Color;
import javax.swing.DefaultListModel;

/**
 *
 * @author pedro
 */
public class ClienteEndereco extends javax.swing.JFrame {
    private Cliente cliente;
    private boolean cadastrar = false;
    
    /**
     * Creates new form AdministratorManagement
     */
    public ClienteEndereco() {
        super("ELETRONICS");
        initComponents();
        getContentPane().setBackground(Color.WHITE);
        logoTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Eletronics/view/midias/logoTop.png")));
    }
    
    public ClienteEndereco(Cliente cliente) {
        super("ELETRONICS");
        initComponents();
        this.cliente = cliente;
        getContentPane().setBackground(Color.WHITE);
        logoTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Eletronics/view/midias/logoTop.png")));
        Campo_Lista.setCellRenderer(new RenderizadorCinco());
        Campo_Lista.setModel(EnderecoServices.trazerEnderecos(cliente));
        if (Campo_Lista.getModel().getSize() > 0)
            Campo_Lista.setSelectedIndex(0);
        this.selecionar();
    }
    
    private void selecionar(){
        if (Campo_Lista.getModel().getSize() > 0) {
            DefaultListModel modelo = (DefaultListModel) Campo_Lista.getModel();
            Endereco endereco = (Endereco) modelo.getElementAt(Campo_Lista.getSelectedIndex());
            Campo_CEP.setText(endereco.getCEP());
            Campo_Rua.setText(endereco.getRua());
            Campo_Numero.setText(endereco.getNumero());
            Campo_Bairro.setText(endereco.getBairro());
            Campo_Cidade.setText(endereco.getCidade());
        }
    }
    
    private void fecharCompra(Endereco endereco) {
        CompraServices.comprar(cliente, endereco);
        ClienteCarrinho clienteCarrinho =  new ClienteCarrinho(this.cliente);
        clienteCarrinho.setVisible(true);
        this.dispose();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new com.Eletronics.view.TelaInicial.jPanelGradient();
        logoTop = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        perfil = new javax.swing.JLabel();
        aboutButton = new javax.swing.JLabel();
        cancelar = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        Campo_Lista = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        novo = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Campo_Texto = new javax.swing.JLabel();
        Campo_CEP = new javax.swing.JTextField();
        Campo_Rua = new javax.swing.JTextField();
        Campo_Numero = new javax.swing.JTextField();
        Campo_Bairro = new javax.swing.JTextField();
        Campo_Cidade = new javax.swing.JTextField();
        selecionar = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Nortar", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("LOGIN");

        jLabel3.setFont(new java.awt.Font("Nortar", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("LOGIN");

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(java.awt.Color.darkGray);

        jLabel1.setFont(new java.awt.Font("Nortar", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ELETRONICS");

        perfil.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        perfil.setForeground(new java.awt.Color(204, 204, 204));
        perfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        perfil.setText("MEU PERFIL");
        perfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                perfilMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                perfilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                perfilMouseExited(evt);
            }
        });

        aboutButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        aboutButton.setForeground(new java.awt.Color(204, 204, 204));
        aboutButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aboutButton.setText("SOBRE");
        aboutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aboutButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aboutButtonMouseExited(evt);
            }
        });

        cancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancelar.setForeground(java.awt.Color.pink);
        cancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancelar.setText("CANCELAR");
        cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoTop, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(perfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)))
                            .addComponent(aboutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(logoTop, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(perfil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                .addComponent(cancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aboutButton)
                .addGap(40, 40, 40))
        );

        scrollPane.setBackground(new java.awt.Color(255, 255, 255));
        scrollPane.setBorder(null);
        scrollPane.setForeground(new java.awt.Color(0, 0, 0));
        scrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Campo_Lista.setBackground(new java.awt.Color(255, 255, 255));
        Campo_Lista.setBorder(null);
        Campo_Lista.setForeground(new java.awt.Color(0, 0, 0));
        Campo_Lista.setFixedCellHeight(30);
        Campo_Lista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Campo_ListaMouseClicked(evt);
            }
        });
        scrollPane.setViewportView(Campo_Lista);

        jLabel5.setFont(new java.awt.Font("Nortar", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("MEUS LOCAIS");

        novo.setBackground(new java.awt.Color(0, 0, 0));
        novo.setFont(new java.awt.Font("Nortar", 0, 14)); // NOI18N
        novo.setForeground(new java.awt.Color(255, 255, 255));
        novo.setText("NOVO LOCAL");
        novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Nortar", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("ENTREGA");

        Campo_Texto.setFont(new java.awt.Font("Nortar", 0, 36)); // NOI18N
        Campo_Texto.setForeground(new java.awt.Color(0, 0, 0));
        Campo_Texto.setText("DADOS");

        Campo_CEP.setEditable(false);
        Campo_CEP.setBackground(new java.awt.Color(255, 255, 255));
        Campo_CEP.setForeground(new java.awt.Color(0, 0, 0));
        Campo_CEP.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CEP", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        Campo_Rua.setEditable(false);
        Campo_Rua.setBackground(new java.awt.Color(255, 255, 255));
        Campo_Rua.setForeground(new java.awt.Color(0, 0, 0));
        Campo_Rua.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "rua", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        Campo_Numero.setEditable(false);
        Campo_Numero.setBackground(new java.awt.Color(255, 255, 255));
        Campo_Numero.setForeground(new java.awt.Color(0, 0, 0));
        Campo_Numero.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "número", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        Campo_Bairro.setEditable(false);
        Campo_Bairro.setBackground(new java.awt.Color(255, 255, 255));
        Campo_Bairro.setForeground(new java.awt.Color(0, 0, 0));
        Campo_Bairro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "bairro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        Campo_Cidade.setEditable(false);
        Campo_Cidade.setBackground(new java.awt.Color(255, 255, 255));
        Campo_Cidade.setForeground(new java.awt.Color(0, 0, 0));
        Campo_Cidade.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "cidade", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        selecionar.setBackground(new java.awt.Color(255, 255, 255));
        selecionar.setFont(new java.awt.Font("Nortar", 0, 14)); // NOI18N
        selecionar.setForeground(new java.awt.Color(0, 0, 0));
        selecionar.setText("ENTREGAR");
        selecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(novo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Campo_Texto)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Campo_Rua, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Campo_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Campo_CEP)
                    .addComponent(Campo_Bairro)
                    .addComponent(Campo_Cidade)
                    .addComponent(selecionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Campo_Texto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Campo_CEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Campo_Rua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Campo_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Campo_Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Campo_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(novo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarMouseEntered
        // TODO add your handling code here:
        cancelar.setForeground(Color.RED);
    }//GEN-LAST:event_cancelarMouseEntered

    private void cancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarMouseExited
        // TODO add your handling code here:
        cancelar.setForeground(Color.PINK);
    }//GEN-LAST:event_cancelarMouseExited

    private void cancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarMouseClicked
        // TODO add your handling code here:
        ClienteCarrinho clienteCarrinho =  new ClienteCarrinho(this.cliente);
        clienteCarrinho.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelarMouseClicked

    private void aboutButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutButtonMouseExited
        // TODO add your handling code here:
        aboutButton.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_aboutButtonMouseExited

    private void aboutButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutButtonMouseEntered
        // TODO add your handling code here:
        aboutButton.setForeground(Color.WHITE);
    }//GEN-LAST:event_aboutButtonMouseEntered

    private void perfilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_perfilMouseExited
        // TODO add your handling code here:
        perfil.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_perfilMouseExited

    private void perfilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_perfilMouseEntered
        // TODO add your handling code here:
        perfil.setForeground(Color.WHITE);
    }//GEN-LAST:event_perfilMouseEntered

    private void novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoActionPerformed
        // TODO add your handling code here:
        if (cadastrar) {
            cadastrar = false;
            
            novo.setText("NOVO LOCAL");
            Campo_Texto.setText("DADOS");
            selecionar.setText("ENTREGAR");
            
            if (Campo_Lista.getModel().getSize() > 0)
                Campo_Lista.setSelectedIndex(0);
            this.selecionar();
            
            Campo_CEP.setEditable(false);
            Campo_Rua.setEditable(false);
            Campo_Numero.setEditable(false);
            Campo_Bairro.setEditable(false);
            Campo_Cidade.setEditable(false);
        } else {
            cadastrar = true;
            
            novo.setText("CANCELAR");
            Campo_Texto.setText("NOVO");
            selecionar.setText("CADASTRAR");
            
            
            Campo_CEP.setText("");
            Campo_Rua.setText("");
            Campo_Numero.setText("");
            Campo_Bairro.setText("");
            Campo_Cidade.setText("");
            
            Campo_CEP.setEditable(true);
            Campo_Rua.setEditable(true);
            Campo_Numero.setEditable(true);
            Campo_Bairro.setEditable(true);
            Campo_Cidade.setEditable(true);
        }
    }//GEN-LAST:event_novoActionPerformed

    private void selecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarActionPerformed
        // TODO add your handling code here:
        if (cadastrar) {
            String CEP = Campo_CEP.getText();
            String rua = Campo_Rua.getText();
            String numero = Campo_Numero.getText();
            String bairro = Campo_Bairro.getText();
            String cidade = Campo_Cidade.getText();
            
            if (CEP.isEmpty() || rua.isEmpty() || numero.isEmpty() || bairro.isEmpty() || cidade.isEmpty()) {
                Warning warning = new Warning("Dados incorretos.");
                warning.setVisible(true);
                
                Campo_CEP.setText("");
                Campo_Rua.setText("");
                Campo_Numero.setText("");
                Campo_Bairro.setText("");
                Campo_Cidade.setText("");
            } else {
                Endereco endereco = new Endereco(this.cliente.getID(), CEP, rua, numero, bairro, cidade);
                EnderecoServices.registrar(endereco);
                this.fecharCompra(endereco);
            }
        } else if (Campo_Lista.getSelectedIndex() != -1) {
            DefaultListModel modelo = (DefaultListModel) Campo_Lista.getModel();
            Endereco endereco = (Endereco) modelo.getElementAt(Campo_Lista.getSelectedIndex());
            this.fecharCompra(endereco);
        } else {
            Warning warning = new Warning("Selecione algum local.");
            warning.setVisible(true);
        }
    }//GEN-LAST:event_selecionarActionPerformed

    private void Campo_ListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Campo_ListaMouseClicked
        // TODO add your handling code here:
        cadastrar = false;
            
        novo.setText("NOVO LOCAL");
        Campo_Texto.setText("DADOS");
        selecionar.setText("ENTREGAR");
            
        Campo_CEP.setEditable(false);
        Campo_Rua.setEditable(false);
        Campo_Numero.setEditable(false);
        Campo_Bairro.setEditable(false);
        Campo_Cidade.setEditable(false);
        
        this.selecionar();
    }//GEN-LAST:event_Campo_ListaMouseClicked

    private void perfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_perfilMouseClicked
        // TODO add your handling code here:
        ClientePerfil clientePerfil = new ClientePerfil(cliente);
        clientePerfil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_perfilMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteEndereco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Campo_Bairro;
    private javax.swing.JTextField Campo_CEP;
    private javax.swing.JTextField Campo_Cidade;
    private javax.swing.JList<String> Campo_Lista;
    private javax.swing.JTextField Campo_Numero;
    private javax.swing.JTextField Campo_Rua;
    private javax.swing.JLabel Campo_Texto;
    private javax.swing.JLabel aboutButton;
    private javax.swing.JLabel cancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logoTop;
    private javax.swing.JButton novo;
    private javax.swing.JLabel perfil;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JButton selecionar;
    // End of variables declaration//GEN-END:variables
}
