package com.Eletronics.view;

import com.Eletronics.model.Cliente;
import com.Eletronics.model.Pedido;
import com.Eletronics.services.CarrinhoServices;
import com.Eletronics.services.PedidoServices;
import com.Eletronics.services.renderers.RenderizadorTres;
import com.Eletronics.services.tools.Warning;
import java.awt.Color;
import javax.swing.DefaultListModel;

public class ClienteCarrinho extends javax.swing.JFrame {
    private boolean visivel = false;
    private Cliente cliente;
    
    public ClienteCarrinho() {
        super("ELETRONICS");
        initComponents();
        atualizar.setVisible(false);
        scrollPane2.setVisible(visivel);
        getContentPane().setBackground(Color.WHITE);
        logoTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Eletronics/view/midias/logoTop.png")));
        excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Eletronics/view/midias/trashIcon.png")));
    }
    
    public ClienteCarrinho(Cliente cliente) {
        super("ELETRONICS");
        initComponents();
        this.cliente = cliente;
        atualizar.setVisible(false);
        scrollPane2.setVisible(visivel);
        getContentPane().setBackground(Color.WHITE);
        Campo_Lista.setCellRenderer(new RenderizadorTres());
        logoTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Eletronics/view/midias/logoTop.png")));
        excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Eletronics/view/midias/trashIcon.png")));
        Campo_Lista.setModel(PedidoServices.trazerPedidos(cliente));
        Campo_Valor.setText("R$ "+CarrinhoServices.definirValortotal(Campo_Lista));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new com.Eletronics.view.TelaInicial.jPanelGradient();
        logoTop = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        perfil = new javax.swing.JLabel();
        aboutButton = new javax.swing.JLabel();
        backButton = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        Campo_Lista = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        finalizePurchase = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Campo_Nome = new javax.swing.JLabel();
        JLabel = new javax.swing.JLabel();
        Campo_Quantidade = new javax.swing.JLabel();
        atualizar = new javax.swing.JButton();
        JLabel1 = new javax.swing.JLabel();
        Campo_Valor = new javax.swing.JLabel();
        excluir = new javax.swing.JButton();
        scrollPane2 = new javax.swing.JScrollPane();
        Campo_Lista2 = new javax.swing.JList<>();

        jLabel2.setFont(new java.awt.Font("Nortar", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("LOGIN");

        jLabel3.setFont(new java.awt.Font("Nortar", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("LOGIN");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(java.awt.Color.darkGray);

        jLabel1.setFont(new java.awt.Font("Nortar", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ELETRONICS");

        perfil.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        perfil.setForeground(new java.awt.Color(204, 204, 204));
        perfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        perfil.setText("MEU PERFIL");
        perfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                perfilMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                perfilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                perfilMouseExited(evt);
            }
        });

        aboutButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        aboutButton.setForeground(new java.awt.Color(204, 204, 204));
        aboutButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aboutButton.setText("SOBRE");
        aboutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aboutButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aboutButtonMouseExited(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backButton.setForeground(new java.awt.Color(204, 204, 204));
        backButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backButton.setText("VOLTAR");
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backButtonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoTop, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(perfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)))
                            .addComponent(aboutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(logoTop, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(perfil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aboutButton)
                .addGap(40, 40, 40))
        );

        jLabel4.setFont(new java.awt.Font("Nortar", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("CARRINHO");

        scrollPane.setBackground(new java.awt.Color(255, 255, 255));
        scrollPane.setBorder(null);
        scrollPane.setForeground(new java.awt.Color(0, 0, 0));
        scrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Campo_Lista.setBackground(new java.awt.Color(255, 255, 255));
        Campo_Lista.setBorder(null);
        Campo_Lista.setForeground(new java.awt.Color(0, 0, 0));
        Campo_Lista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Campo_ListaMouseClicked(evt);
            }
        });
        scrollPane.setViewportView(Campo_Lista);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("CLIQUE PARA MAIS DETALHES");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("DETALHES");

        finalizePurchase.setBackground(new java.awt.Color(0, 0, 0));
        finalizePurchase.setFont(new java.awt.Font("Nortar", 0, 14)); // NOI18N
        finalizePurchase.setForeground(new java.awt.Color(255, 255, 255));
        finalizePurchase.setText("FECHAR CARRINHO");
        finalizePurchase.setBorder(null);
        finalizePurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizePurchaseActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Nortar", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("ITEM");

        Campo_Nome.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Campo_Nome.setForeground(new java.awt.Color(0, 0, 0));
        Campo_Nome.setText("SELECIONE");

        JLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JLabel.setForeground(new java.awt.Color(0, 0, 0));
        JLabel.setText("Quantidade");

        Campo_Quantidade.setForeground(new java.awt.Color(153, 153, 153));
        Campo_Quantidade.setText("Alterar");
        Campo_Quantidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Campo_QuantidadeMouseClicked(evt);
            }
        });

        atualizar.setBackground(new java.awt.Color(255, 255, 255));
        atualizar.setFont(new java.awt.Font("Nortar", 0, 14)); // NOI18N
        atualizar.setForeground(new java.awt.Color(0, 0, 0));
        atualizar.setText("ATUALIZAR");
        atualizar.setBorder(null);
        atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarActionPerformed(evt);
            }
        });

        JLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JLabel1.setForeground(new java.awt.Color(0, 0, 0));
        JLabel1.setText("TOTAL CARRINHO");

        Campo_Valor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Campo_Valor.setForeground(new java.awt.Color(0, 0, 0));
        Campo_Valor.setText("R$ 0000.0");

        excluir.setBackground(new java.awt.Color(255, 255, 255));
        excluir.setForeground(new java.awt.Color(0, 0, 0));
        excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirActionPerformed(evt);
            }
        });

        scrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        scrollPane2.setBorder(null);
        scrollPane2.setForeground(new java.awt.Color(0, 0, 0));
        scrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Campo_Lista2.setBackground(new java.awt.Color(255, 255, 255));
        Campo_Lista2.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 0, 5, 5));
        Campo_Lista2.setForeground(new java.awt.Color(0, 0, 0));
        Campo_Lista2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "x1", "x2", "x3", "x4", "x5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        Campo_Lista2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Campo_Lista2MouseClicked(evt);
            }
        });
        scrollPane2.setViewportView(Campo_Lista2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Campo_Nome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Campo_Quantidade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(finalizePurchase, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(Campo_Valor, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrollPane))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(Campo_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JLabel)
                        .addGap(0, 0, 0)
                        .addComponent(Campo_Quantidade)
                        .addGap(0, 0, 0)
                        .addComponent(scrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(atualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addComponent(JLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Campo_Valor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(finalizePurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void perfilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_perfilMouseEntered
        // TODO add your handling code here:
        perfil.setForeground(Color.WHITE);
    }//GEN-LAST:event_perfilMouseEntered

    private void perfilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_perfilMouseExited
        // TODO add your handling code here:
        perfil.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_perfilMouseExited

    private void aboutButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutButtonMouseEntered
        // TODO add your handling code here:
        aboutButton.setForeground(Color.WHITE);
    }//GEN-LAST:event_aboutButtonMouseEntered

    private void aboutButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutButtonMouseExited
        // TODO add your handling code here:
        aboutButton.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_aboutButtonMouseExited

    private void backButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseEntered
        // TODO add your handling code here:
        backButton.setForeground(Color.WHITE);
    }//GEN-LAST:event_backButtonMouseEntered

    private void backButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseExited
        // TODO add your handling code here:
        backButton.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_backButtonMouseExited

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        // TODO add your handling code here:
        ClienteMain clienteMain = new ClienteMain(cliente);
        clienteMain.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonMouseClicked

    private void Campo_ListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Campo_ListaMouseClicked
        // TODO add your handling code here:
        if (Campo_Lista.getModel().getSize() > 0) {
            DefaultListModel modelo = (DefaultListModel) Campo_Lista.getModel();
            Pedido pedido = (Pedido) modelo.getElementAt(Campo_Lista.getSelectedIndex());
            Campo_Nome.setText(pedido.getProduto().getNome().toUpperCase());
            atualizar.setVisible(false);
        }
    }//GEN-LAST:event_Campo_ListaMouseClicked

    private void Campo_QuantidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Campo_QuantidadeMouseClicked
        // TODO add your handling code here:
        if (Campo_Lista.getSelectedIndex() != -1) {
            if (!visivel) {
                visivel = true;
                scrollPane2.setSize(220, 110);
            } else
                visivel = false;
            scrollPane2.setVisible(visivel);
        } else {
            Warning warning = new Warning("Selecione algum item.");
            warning.setVisible(true);
        }
    }//GEN-LAST:event_Campo_QuantidadeMouseClicked

    private void finalizePurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizePurchaseActionPerformed
        // TODO add your handling code here:
        if (Campo_Lista.getModel().getSize() > 0) {
            ClienteEndereco clienteEndereco = new ClienteEndereco(this.cliente);
            clienteEndereco.setVisible(true);
            this.dispose();
        } else {
            Warning warning = new Warning("Adicione algum item.");
            warning.setVisible(true);
        }
    }//GEN-LAST:event_finalizePurchaseActionPerformed

    private void Campo_Lista2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Campo_Lista2MouseClicked
        // TODO add your handling code here:
        Campo_Quantidade.setText(String.valueOf(Campo_Lista2.getSelectedIndex()+1));
        atualizar.setVisible(true);
    }//GEN-LAST:event_Campo_Lista2MouseClicked

    private void atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarActionPerformed
        // TODO add your handling code here:
        DefaultListModel modelo = (DefaultListModel) Campo_Lista.getModel();
        Pedido pedido = (Pedido) modelo.getElementAt(Campo_Lista.getSelectedIndex());
        
        pedido.setQuantidade(Integer.parseInt(Campo_Quantidade.getText()));
        pedido.setValor(pedido.getQuantidade()*pedido.getProduto().getValor());
        PedidoServices.atualizar(pedido);
        
        Campo_Quantidade.setText("Alterar");
        int indice = Campo_Lista.getSelectedIndex();
        Campo_Lista.setModel(PedidoServices.trazerPedidos(cliente));
        Campo_Valor.setText("R$ "+CarrinhoServices.definirValortotal(Campo_Lista));
        Campo_Nome.setText(pedido.getProduto().getNome().toUpperCase());
        Campo_Lista.setSelectedIndex(indice);
        atualizar.setVisible(false);
    }//GEN-LAST:event_atualizarActionPerformed

    private void excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirActionPerformed
        // TODO add your handling code here:
        if (Campo_Lista.getSelectedIndex() != -1) {
            DefaultListModel modelo = (DefaultListModel) Campo_Lista.getModel();
            Pedido pedido = (Pedido) modelo.getElementAt(Campo_Lista.getSelectedIndex());
            
            PedidoServices.excluir(pedido);
            
            atualizar.setVisible(false);
            Campo_Nome.setText("SELECIONE");
            Campo_Quantidade.setText("Alterar");
            Campo_Lista.setModel(PedidoServices.trazerPedidos(cliente));
            Campo_Valor.setText("R$ "+CarrinhoServices.definirValortotal(Campo_Lista));
        } else {
            Warning warning = new Warning("Selecione algum item.");
            warning.setVisible(true);
        }
    }//GEN-LAST:event_excluirActionPerformed

    private void perfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_perfilMouseClicked
        // TODO add your handling code here:
        ClientePerfil clientePerfil = new ClientePerfil(cliente);
        clientePerfil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_perfilMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteCarrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteCarrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteCarrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteCarrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteCarrinho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> Campo_Lista;
    private javax.swing.JList<String> Campo_Lista2;
    private javax.swing.JLabel Campo_Nome;
    private javax.swing.JLabel Campo_Quantidade;
    private javax.swing.JLabel Campo_Valor;
    private javax.swing.JLabel JLabel;
    private javax.swing.JLabel JLabel1;
    private javax.swing.JLabel aboutButton;
    private javax.swing.JButton atualizar;
    private javax.swing.JLabel backButton;
    private javax.swing.JButton excluir;
    private javax.swing.JButton finalizePurchase;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logoTop;
    private javax.swing.JLabel perfil;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JScrollPane scrollPane2;
    // End of variables declaration//GEN-END:variables
}
